config/routes.rb
Rails.application.routes.draw do
  resources :archived_projects

  resources :project_pdocuments
  resources :project_pw9s
  resources :project_invoices
  resources :project_prevcontracts
  resources :project_pcontracts
  resources :project_pproposals
  resources :project_cicons
  resources :services
  resources :project_picons
  resources :services
  resources :project_picons
  resources :projects
  resources :associate_drivers_insurances
  resources :associate_drivers_licenses
  resources :associate_direct_deposits
  resources :associate_w9s
  resources :associate_contracts
  resources :positions
  resources :wrklocs
  resources :worklocations
  resources :associate_gresumes
  resources :associate_resumes
  resources :associate_attachments
  resources :associates
  devise_for :users, :controllers => { :registrations => 'devise/registrations' }
  resources :users, :only => [:index, :show, :destroy]
  root 'home#index'

end

app/models/associate_contract.rb
class AssociateContract < ActiveRecord::Base
  mount_uploader :contract, ContractUploader
  belongs_to :associate
end

app/controllers/associate_contracts_controller.rb
class AssociateContractsController < ApplicationController
  before_action :set_associate_contract, only: [:show, :edit, :update, :destroy]

  # GET /associate_contracts
  # GET /associate_contracts.json
  def index
    @associate_contracts = AssociateContract.all
  end

  # GET /associate_contracts/1
  # GET /associate_contracts/1.json
  def show
  end

  # GET /associate_contracts/new
  def new
    @associate_contract = AssociateContract.new
  end

  # GET /associate_contracts/1/edit
  def edit
  end

  # POST /associate_contracts
  # POST /associate_contracts.json
  def create
    @associate_contract = AssociateContract.new(associate_contract_params)

    respond_to do |format|
      if @associate_contract.save
        format.html { redirect_to @associate_contract, notice: 'Associate contract was successfully created.' }
        format.json { render :show, status: :created, location: @associate_contract }
      else
        format.html { render :new }
        format.json { render json: @associate_contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associate_contracts/1
  # PATCH/PUT /associate_contracts/1.json
  def update
    respond_to do |format|
      if @associate_contract.update(associate_contract_params)
        format.html { redirect_to @associate_contract.associate, notice: 'Associate contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @associate_contract }
      else
        format.html { render :edit }
        format.json { render json: @associate_contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associate_contracts/1
  # DELETE /associate_contracts/1.json
  def destroy
    @associate_contract.destroy
    respond_to do |format|
      format.html { redirect_to @associate_contract.associate, notice: 'Associate contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associate_contract
      @associate_contract = AssociateContract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associate_contract_params
      params.require(:associate_contract).permit(:associate_id, :contract)
    end
end

app/helpers/associate_contracts_helper.rb
module AssociateContractsHelper
end

app/views/associate_contracts/_form.html.erb
<%= link_to @associate_contract.contract, @associate_contract.contract_url, :target => '_blank'  %>
  <%= form_for(@associate_contract) do |f| %>
    <% if @associate_contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@associate_contract.errors.count, "error") %> prohibited this associate_contract from being saved:</h2>

      <ul>
      <% @associate_contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :contract %><br>
      <%= f.file_field :contract %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/associate_contracts/edit.html.erb
<h1>Editing Associate Contract</h1>

<%= render 'form' %>

<%#= link_to 'Show', @associate_contract %>
<%#= link_to 'Back', associate_contracts_path %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              associate_path(@associate_contract.associate_id), :class => 'btn btn-primary'  %>

app/views/associate_contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Associate Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Associate</th>
      <th>Contract</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @associate_contracts.each do |associate_contract| %>
      <tr>
        <td><%= associate_contract.associate_id %></td>
        <td><%= associate_contract.contract %></td>
        <td><%= link_to 'Show', associate_contract %></td>
        <td><%= link_to 'Edit', edit_associate_contract_path(associate_contract) %></td>
        <td><%= link_to 'Destroy', associate_contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Associate contract', new_associate_contract_path %>

app/views/associate_contracts/new.html.erb
<h1>New Associate Contract</h1>

<%= render 'form' %>

<%= link_to 'Back', associate_contracts_path %>

app/views/associate_contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Associate:</strong>
  <%= @associate_contract.associate_id %>
</p>

<p>
  <strong>Contract:</strong>
  <%= @associate_contract.contract %>
</p>

<%= link_to 'Edit', edit_associate_contract_path(@associate_contract) %> |
<%= link_to 'Back', associate_contracts_path %>