config/routes.rb
Rails.application.routes.draw do
  resources :archived_projects

  resources :project_pdocuments
  resources :project_pw9s
  resources :project_invoices
  resources :project_prevcontracts
  resources :project_pcontracts
  resources :project_pproposals
  resources :project_cicons
  resources :services
  resources :project_picons
  resources :services
  resources :project_picons
  resources :projects
  resources :associate_drivers_insurances
  resources :associate_drivers_licenses
  resources :associate_direct_deposits
  resources :associate_w9s
  resources :associate_contracts
  resources :positions
  resources :wrklocs
  resources :worklocations
  resources :associate_gresumes
  resources :associate_resumes
  resources :associate_attachments
  resources :associates
  devise_for :users, :controllers => { :registrations => 'devise/registrations' }
  resources :users, :only => [:index, :show, :destroy]
  root 'home#index'

end

app/models/project_pproposal.rb
class ProjectPproposal < ActiveRecord::Base
  mount_uploader :pproposal, PproposalUploader
  belongs_to :project
end

app/controllers/project_pproposals_controller.rb
class ProjectPproposalsController < ApplicationController
  before_action :set_project_pproposal, only: [:show, :edit, :update, :destroy]

  # GET /project_pproposals
  # GET /project_pproposals.json
  def index
    @project_pproposals = ProjectPproposal.all
  end

  # GET /project_pproposals/1
  # GET /project_pproposals/1.json
  def show
  end

  # GET /project_pproposals/new
  def new
    @project_pproposal = ProjectPproposal.new
  end

  # GET /project_pproposals/1/edit
  def edit
  end

  # POST /project_pproposals
  # POST /project_pproposals.json
  def create
    @project_pproposal = ProjectPproposal.new(project_pproposal_params)

    respond_to do |format|
      if @project_pproposal.save
        format.html { redirect_to @project_pproposal, notice: 'Project pproposal was successfully created.' }
        format.json { render :show, status: :created, location: @project_pproposal }
      else
        format.html { render :new }
        format.json { render json: @project_pproposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_pproposals/1
  # PATCH/PUT /project_pproposals/1.json
  def update
    respond_to do |format|
      if @project_pproposal.update(project_pproposal_params)
        format.html { redirect_to @project_pproposal.project, notice: 'Project pproposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_pproposal }
      else
        format.html { render :edit }
        format.json { render json: @project_pproposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_pproposals/1
  # DELETE /project_pproposals/1.json
  def destroy
    @project_pproposal.destroy
    respond_to do |format|
      format.html { redirect_to @project_pproposal.project, notice: 'Project pproposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_pproposal
      @project_pproposal = ProjectPproposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_pproposal_params
      params.require(:project_pproposal).permit(:project_id, :pproposal)
    end
end

app/helpers/project_pproposals_helper.rb
module ProjectPproposalsHelper
end

app/views/project_pproposals/_form.html.erb
<%= link_to @project_pproposal.pproposal, @project_pproposal.pproposal_url, :target => '_blank'  %>
  <%= form_for(@project_pproposal) do |f| %>
    <% if @project_pproposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_pproposal.errors.count, "error") %> prohibited this project_pproposal from being saved:</h2>

      <ul>
      <% @project_pproposal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :pproposal %><br>
      <%= f.file_field :pproposal, :id => "image_picture" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/project_pproposals/edit.html.erb
<h1>Editing Project Pproposal</h1>

<%= render 'form' %>

<%#= link_to 'Show', @project_pproposal %> |
<%#= link_to 'Back', project_pproposals_path %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              @project_pproposal.project, :class => 'btn btn-default'  %>

app/views/project_pproposals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Project Pproposals</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Pproposal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_pproposals.each do |project_pproposal| %>
      <tr>
        <td><%= project_pproposal.project_id %></td>
        <td><%= project_pproposal.pproposal %></td>
        <td><%= link_to 'Show', project_pproposal %></td>
        <td><%= link_to 'Edit', edit_project_pproposal_path(project_pproposal) %></td>
        <td><%= link_to 'Destroy', project_pproposal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project pproposal', new_project_pproposal_path %>

app/views/project_pproposals/new.html.erb
<h1>New Project Pproposal</h1>

<%= render 'form' %>

<%= link_to 'Back', project_pproposals_path %>

app/views/project_pproposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @project_pproposal.project_id %>
</p>

<p>
  <strong>Pproposal:</strong>
  <%= @project_pproposal.pproposal %>
</p>

<%= link_to 'Edit', edit_project_pproposal_path(@project_pproposal) %> |
<%= link_to 'Back', project_pproposals_path %>