config/routes.rb
Rails.application.routes.draw do
  resources :archived_projects

  resources :project_pdocuments
  resources :project_pw9s
  resources :project_invoices
  resources :project_prevcontracts
  resources :project_pcontracts
  resources :project_pproposals
  resources :project_cicons
  resources :services
  resources :project_picons
  resources :services
  resources :project_picons
  resources :projects
  resources :associate_drivers_insurances
  resources :associate_drivers_licenses
  resources :associate_direct_deposits
  resources :associate_w9s
  resources :associate_contracts
  resources :positions
  resources :wrklocs
  resources :worklocations
  resources :associate_gresumes
  resources :associate_resumes
  resources :associate_attachments
  resources :associates
  devise_for :users, :controllers => { :registrations => 'devise/registrations' }
  resources :users, :only => [:index, :show, :destroy]
  root 'home#index'

end

app/models/associate_resume.rb
class AssociateResume < ActiveRecord::Base
  mount_uploader :resume, ResumeUploader
  belongs_to :associate
end

app/controllers/associate_resumes_controller.rb
class AssociateResumesController < ApplicationController
  before_action :set_associate_resume, only: [:show, :edit, :update, :destroy]

  # GET /associate_resumes
  # GET /associate_resumes.json
  def index
    @associate_resumes = AssociateResume.all
  end

  # GET /associate_resumes/1
  # GET /associate_resumes/1.json
  def show
  end

  # GET /associate_resumes/new
  def new
    @associate_resume = AssociateResume.new
  end

  # GET /associate_resumes/1/edit
  def edit
  end

  # POST /associate_resumes
  # POST /associate_resumes.json
  def create
    @associate_resume = AssociateResume.new(associate_resume_params)

    respond_to do |format|
      if @associate_resume.save
        format.html { redirect_to @associate_resume, notice: 'Associate resume was successfully created.' }
        format.json { render :show, status: :created, location: @associate_resume }
      else
        format.html { render :new }
        format.json { render json: @associate_resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associate_resumes/1
  # PATCH/PUT /associate_resumes/1.json
  def update
    respond_to do |format|
      if @associate_resume.update(associate_resume_params)
        format.html { redirect_to @associate_resume.associate, notice: 'Associate resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @associate_resume }
      else
        format.html { render :edit }
        format.json { render json: @associate_resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associate_resumes/1
  # DELETE /associate_resumes/1.json
  def destroy
    @associate_resume.destroy
    respond_to do |format|
      format.html { redirect_to @associate_resume.associate, notice: 'Associate resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associate_resume
      @associate_resume = AssociateResume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associate_resume_params
      params.require(:associate_resume).permit(:associate_id, :resume)
    end
end

app/helpers/associate_resumes_helper.rb
module AssociateResumesHelper
end

app/views/associate_resumes/_form.html.erb
<%= link_to @associate_resume.resume, @associate_resume.resume_url, :target => '_blank'  %>
  <%= form_for(@associate_resume) do |f| %>
    <% if @associate_resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@associate_resume.errors.count, "error") %> prohibited this associate_resume from being saved:</h2>

      <ul>
      <% @associate_resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :resume %><br>
      <%= f.file_field :resume %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/associate_resumes/edit.html.erb
<h1>Editing Associate Resume</h1>

<%= render 'form' %>

<%#= link_to 'Show', @associate_resume %>
<%#= link_to 'Back', associate_resumes_path %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              associate_path(@associate_resume.associate_id), :class => 'btn btn-primary'  %>

app/views/associate_resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Associate Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Associate</th>
      <th>Resume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @associate_resumes.each do |associate_resume| %>
      <tr>
        <td><%= associate_resume.associate_id %></td>
        <td><%= associate_resume.resume %></td>
        <td><%= link_to 'Show', associate_resume %></td>
        <td><%= link_to 'Edit', edit_associate_resume_path(associate_resume) %></td>
        <td><%= link_to 'Destroy', associate_resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Associate resume', new_associate_resume_path %>

app/views/associate_resumes/new.html.erb
<h1>New Associate Resume</h1>

<%= render 'form' %>

<%= link_to 'Back', associate_resumes_path %>

app/views/associate_resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Associate:</strong>
  <%= @associate_resume.associate_id %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @associate_resume.resume %>
</p>

<%= link_to 'Edit', edit_associate_resume_path(@associate_resume) %> |
<%= link_to 'Back', associate_resumes_path %>