config/routes.rb
Rails.application.routes.draw do
  resources :archived_projects

  resources :project_pdocuments
  resources :project_pw9s
  resources :project_invoices
  resources :project_prevcontracts
  resources :project_pcontracts
  resources :project_pproposals
  resources :project_cicons
  resources :services
  resources :project_picons
  resources :services
  resources :project_picons
  resources :projects
  resources :associate_drivers_insurances
  resources :associate_drivers_licenses
  resources :associate_direct_deposits
  resources :associate_w9s
  resources :associate_contracts
  resources :positions
  resources :wrklocs
  resources :worklocations
  resources :associate_gresumes
  resources :associate_resumes
  resources :associate_attachments
  resources :associates
  devise_for :users, :controllers => { :registrations => 'devise/registrations' }
  resources :users, :only => [:index, :show, :destroy]
  root 'home#index'

end

app/models/wrkloc.rb
class Wrkloc < ActiveRecord::Base
    has_and_belongs_to_many :associates, dependent: :destroy
end

app/controllers/wrklocs_controller.rb
class WrklocsController < ApplicationController
  before_action :set_wrkloc, only: [:show, :edit, :update, :destroy]

  # GET /wrklocs
  # GET /wrklocs.json
  def index
    @wrklocs = Wrkloc.all
  end

  # GET /wrklocs/1
  # GET /wrklocs/1.json
  def show
  end

  # GET /wrklocs/new
  def new
    @wrkloc = Wrkloc.new
  end

  # GET /wrklocs/1/edit
  def edit
  end

  # POST /wrklocs
  # POST /wrklocs.json
  def create
    @wrkloc = Wrkloc.new(wrkloc_params)

    respond_to do |format|
      if @wrkloc.save
        format.html { redirect_to @wrkloc, notice: 'Wrkloc was successfully created.' }
        format.json { render :show, status: :created, location: @wrkloc }
      else
        format.html { render :new }
        format.json { render json: @wrkloc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrklocs/1
  # PATCH/PUT /wrklocs/1.json
  def update
    respond_to do |format|
      if @wrkloc.update(wrkloc_params)
        format.html { redirect_to @wrkloc, notice: 'Wrkloc was successfully updated.' }
        format.json { render :show, status: :ok, location: @wrkloc }
      else
        format.html { render :edit }
        format.json { render json: @wrkloc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrklocs/1
  # DELETE /wrklocs/1.json
  def destroy
    @wrkloc.destroy
    respond_to do |format|
      format.html { redirect_to wrklocs_url, notice: 'Wrkloc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrkloc
      @wrkloc = Wrkloc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wrkloc_params
      params.require(:wrkloc).permit(:wrkstate)
    end
end

app/helpers/wrklocs_helper.rb
module WrklocsHelper
end

app/views/wrklocs/_form.html.erb
<%= form_for(@wrkloc) do |f| %>
  <% if @wrkloc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wrkloc.errors.count, "error") %> prohibited this wrkloc from being saved:</h2>

      <ul>
      <% @wrkloc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wrkstate %><br>
    <%= f.text_field :wrkstate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wrklocs/edit.html.erb
<h1>Editing Wrkloc</h1>

<%= render 'form' %>

<%= link_to 'Show', @wrkloc %> |
<%= link_to 'Back', wrklocs_path %>

app/views/wrklocs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wrklocs</h1>

<table>
  <thead>
    <tr>
      <th>Wrkstate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wrklocs.each do |wrkloc| %>
      <tr>
        <td><%= wrkloc.wrkstate %></td>
        <td><%= link_to 'Show', wrkloc %></td>
        <td><%= link_to 'Edit', edit_wrkloc_path(wrkloc) %></td>
        <td><%= link_to 'Destroy', wrkloc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wrkloc', new_wrkloc_path %>

app/views/wrklocs/new.html.erb
<h1>New Wrkloc</h1>

<%= render 'form' %>

<%= link_to 'Back', wrklocs_path %>

app/views/wrklocs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wrkstate:</strong>
  <%= @wrkloc.wrkstate %>
</p>

<%= link_to 'Edit', edit_wrkloc_path(@wrkloc) %> |
<%= link_to 'Back', wrklocs_path %>